#!/bin/bash

pid=$(ps aux | grep "10-process_and_pid_file" | grep -v grep | awk '{print $2}')
echo "$pid" > /var/run/myscript.pid

_term() {
	rm /var/run/myscript.pid
	echo 'I hate the kill command'
	exit
}

trap _term SIGTERM
trap _term SIGQUIT

trap "echo 'Y U no love me?!'" SIGINT

while true
	do 
	echo "To infinity and beyond"
	sleep 1
done
