#!/bin/bash

array=("start" "stop" "restart")
value=${1}
myPath="/var/run/my_process.pid"

if [[ ! " ${array[*]} " =~ [[:space:]]${value}[[:space:]] ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

if [ $value ==  "start" ]
then
	nohup ./manage_my_process > /dev/null 2>&1 &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ $value == "stop" ]
then
	kill -TERM "$(cat $myPath)"
	rm $myPath
	echo "manage_my_process stopped"
else
	kill -TERM "$(cat $myPath)" 2>/dev/null
        rm $myPath
	nohup ./manage_my_process > /dev/null 2>&1 &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process restarted"
fi
