#!/bin/bash

array=("start" "stop" "restart")
value=${1}
myPath="/var/run/my_process.pid"

if [[ ! " ${array[*]} " =~ [[:space:]]${value}[[:space:]] ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

if [ $value ==  "start" ]
then
	nohup "$DAEMON" > /dev/null 2>&1 &
	pid=$(ps aux | grep "manage_my_process" | grep -v grep | awk '{print $2}')
	echo $pid > $myPath
	echo "manage_my_process started"
elif [ $value == "stop" ]
then
	kill -TERM "$(cat $PID_FILE)" 2>/dev/null
	rm $myPath
	echo "manage_my_process stopped"
else
	kill -TERM "$(cat $PID_FILE)" 2>/dev/null
        rm $myPath
	nohup "$DAEMON" > /dev/null 2>&1 &
        pid=$(ps aux | grep "manage_my_process" | grep -v grep | awk '{print $2}')
        echo $pid > $myPath
	echo "manage_my_process restarted"
fi
